Repository ChrisTimperley/roswire, pull requests merged in 2020-06, with the labels that each got.

#358 Fix the wrong return in locate function of ROSLaunchManager
  src/roswire/proxy/roslaunch/roslaunch.py
Labels: bug

#359 Add ROSLaunchController for controlling ROS launch processes (fixes #354)
  CHANGELOG.md
  src/roswire/proxy/roslaunch/controller.py
  src/roswire/proxy/roslaunch/roslaunch.py
Labels: feature

#366 Added support for name remappings to launch method (fixes #343)
  CHANGELOG.md
  src/roswire/proxy/roslaunch/config/env.py
  src/roswire/proxy/roslaunch/config/launch.py
  src/roswire/proxy/roslaunch/config/node.py
  src/roswire/proxy/roslaunch/config/parameter.py
  src/roswire/proxy/roslaunch/reader.py
  src/roswire/proxy/roslaunch/roslaunch.py
  test/test_roslaunch.py
Labels: enhancement

#372 Add support for eval args in roslaunch XML reader (fixes #267)
  CHANGELOG.md
  src/roswire/proxy/roslaunch/substitution.py
  test/systems/husky.yml
  test/test_roslaunch.py
Labels: enhancement
